set(pyorbit_src
 linac/rfgap/BaseRfGap.cc
 linac/rfgap/BaseRfGap_slow.cc
 linac/rfgap/MatrixRfGap.cc
 linac/rfgap/RfGapThreePointTTF.cc
 linac/rfgap/RfGapThreePointTTF_slow.cc
 linac/rfgap/RfGapTTF.cc
 linac/rfgap/RfGapTTF_slow.cc
 linac/rfgap/SuperFishFieldSource.cc
 linac/rfgap/wrap_BaseRfGap.cc
 linac/rfgap/wrap_BaseRfGap_slow.cc
 linac/rfgap/wrap_MatrixRfGap.cc
 linac/rfgap/wrap_RfGapThreePointTTF.cc
 linac/rfgap/wrap_RfGapThreePointTTF_slow.cc
 linac/rfgap/wrap_RfGapTTF.cc
 linac/rfgap/wrap_RfGapTTF_slow.cc
 linac/rfgap/wrap_SuperFishFieldSource.cc
 linac/tracking/linac_tracking.cc
 linac/tracking/wrap_linac_tracking.cc
 linac/wrap_linacmodule.cc
 mpi/orbit_mpi.cc
 mpi/wrap_mpi_comm.cc
 orbit/Apertures/Aperture.cc
 orbit/Apertures/EnergyAperture.cc
 orbit/Apertures/PhaseAperture.cc
 orbit/Apertures/wrap_aperture.cc
 orbit/Apertures/wrap_EnergyAperture.cc
 orbit/Apertures/wrap_PhaseAperture.cc
 orbit/Apertures/wrap_TAperture.cc
 orbit/Bunch.cc
 orbit/BunchDiagnostics/BunchTuneAnalysis.cc
 orbit/BunchDiagnostics/BunchTwissAnalysis.cc
 orbit/BunchDiagnostics/wrap_bunch_tune_analysis.cc
 orbit/BunchDiagnostics/wrap_bunch_twiss_analysis.cc
 orbit/Errors/errorbase.cc
 orbit/Errors/wrap_errorbase.cc
 orbit/FieldTracker/FieldTracker.cc
 orbit/FieldTracker/wrap_fieldtracker.cc
 orbit/Impedances/LImpedance.cc
 orbit/Impedances/TImpedance.cc
 orbit/Impedances/wrap_impedances.cc
 orbit/Impedances/wrap_LImpedance.cc
 orbit/Impedances/wrap_TImpedance.cc
 orbit/MaterialInteractions/Collimator.cc
 orbit/MaterialInteractions/cross_sections.cc
 orbit/MaterialInteractions/Foil.cc
 orbit/MaterialInteractions/MaterialInteractions.cc
 orbit/MaterialInteractions/numrecipes.cc
 orbit/MaterialInteractions/wrap_collimator.cc
 orbit/MaterialInteractions/wrap_foil.cc
 orbit/OrbitConst.cc
 orbit/ParticlesAttributes/AtomPopulations.cc
 orbit/ParticlesAttributes/Evolution.cc
 orbit/ParticlesAttributes/LostParticleAttributes.cc
 orbit/ParticlesAttributes/ParticleAttributes.cc
 orbit/ParticlesAttributes/ParticleAttributesFactory.cc
 orbit/ParticlesAttributes/ParticleIdNumber.cc
 orbit/ParticlesAttributes/ParticleInitialCoordinates.cc
 orbit/ParticlesAttributes/ParticleMacroSize.cc
 orbit/ParticlesAttributes/ParticlePhaseAttributes.cc
 orbit/ParticlesAttributes/part_time.cc
 orbit/ParticlesAttributes/pq_coordinates.cc
 orbit/ParticlesAttributes/WaveFunctionAmplitudes.cc
 orbit/RFCavities/Barrier_Cav.cc
 orbit/RFCavities/Dual_Harmonic_Cav.cc
 orbit/RFCavities/Frequency_Cav.cc
 orbit/RFCavities/Harmonic_Cav.cc
 orbit/RFCavities/wrap_Barrier_Cav.cc
 orbit/RFCavities/wrap_Dual_Harmonic_Cav.cc
 orbit/RFCavities/wrap_Frequency_Cav.cc
 orbit/RFCavities/wrap_Harmonic_Cav.cc
 orbit/RFCavities/wrap_rfcavities.cc
 orbit/SynchPartRedefinition/SynchPartRedefinitionZdE.cc
 orbit/SynchPartRedefinition/wrap_synch_part_redefinition_z_de.cc
 orbit/SyncPart.cc
 orbit/wrap_bunch.cc
 orbit/wrap_syncpart.cc
 spacecharge/BaseBoundary2D.cc
 spacecharge/ForceSolver2D.cc
 spacecharge/ForceSolverFFT2D.cc
 spacecharge/Grid1D.cc
 spacecharge/Grid2D.cc
 spacecharge/Grid3D.cc
 spacecharge/LSpaceChargeCalc.cc
 spacecharge/PoissonSolver2D.cc
 spacecharge/PoissonSolver3D.cc
 spacecharge/PoissonSolverFFT2D.cc
 spacecharge/PoissonSolverFFT3D.cc
 spacecharge/ShapedBoundary2D.cc
 spacecharge/SpaceChargeCalc2p5D.cc
 spacecharge/SpaceChargeCalc2p5Drb.cc
 spacecharge/SpaceChargeCalc3D.cc
 spacecharge/SpaceChargeCalcSliceBySlice2D.cc
 spacecharge/SpaceChargeCalcUnifEllipse.cc
 spacecharge/SpaceChargeForceCalc2p5D.cc
 spacecharge/UniformEllipsoidFieldCalculator.cc
 spacecharge/wrap_boundary2d.cc
 spacecharge/wrap_forcesolverfft2d.cc
 spacecharge/wrap_grid1D.cc
 spacecharge/wrap_grid2D.cc
 spacecharge/wrap_grid3D.cc
 spacecharge/wrap_lspacechargecalc.cc
 spacecharge/wrap_poissonsolverfft2d.cc
 spacecharge/wrap_poissonsolverfft3d.cc
 spacecharge/wrap_spacechargecalc2p5d.cc
 spacecharge/wrap_spacechargecalc2p5d_rb.cc
 spacecharge/wrap_spacechargecalc3d.cc
 spacecharge/wrap_spacechargecalc_slicebyslice_2D.cc
 spacecharge/wrap_spacechargecalc_uniform_ellipse.cc
 spacecharge/wrap_spacecharge.cc
 spacecharge/wrap_spacechargeforcecalc2p5d.cc
 spacecharge/wrap_uniform_ellipsoid_field_calculator.cc
 teapot/MatrixGenerator.cc
 teapot/teapotbase.cc
 teapot/wrap_matrix_generator.cc
 teapot/wrap_teapotbase.cc
 trackerrk4/ExtEffectsContainer.cc
 trackerrk4/ExternalEffects.cc
 trackerrk4/PyExternalEffects.cc
 trackerrk4/RungeKuttaTracker.cc
 trackerrk4/wrap_ext_effects_container.cc
 trackerrk4/wrap_py_external_effects.cc
 trackerrk4/wrap_runge_kutta_tracker.cc
 trackerrk4/wrap_trackerrk4.cc
 utils/AttributesBucket.cc
 utils/BaseFieldSource.cc
 utils/bessel.cc
 utils/BufferStore.cc
 utils/bunch/BunchExtremaCalculator.cc
 utils/bunch/InitialCoordsAttrFunctions.cc
 utils/bunch/ParticlesWithIdFunctions.cc
 utils/bunch/TwissFilteringFunctions.cc
 utils/bunch/wrap_bunch_extrema_calculator.cc
 utils/bunch/wrap_bunch_utils_functions.cc
 utils/CppPyWrapper.cc
 utils/FieldSourceContainer.cc
 utils/integration/GaussLegendreIntegrator.cc
 utils/integration/gauss_legendre_points.cc
 utils/integration/wrap_gauss_legendre_integrator.cc
 utils/LorentzTransformationEM.cc
 utils/MathPolynomial.cc
 utils/matrix/Matrix.cc
 utils/matrix/MatrixOperations.cc
 utils/matrix/PhaseVector.cc
 utils/matrix/wrap_matrix.cc
 utils/matrix/wrap_phase_vector.cc
 utils/OU_Function.cc
 utils/OU_SplineCH.cc
 utils/polynomial/OU_Polynomial.cc
 utils/polynomial/wrap_polynomial.cc
 utils/PyBaseFieldSource.cc
 utils/Random.cc
 utils/statistics/StatMoments2D.cc
 utils/statistics/wrap_statmoments2d.cc
 utils/StringUtils.cc
 utils/wrap_field_source_container.cc
 utils/wrap_function.cc
 utils/wrap_numrecipes.cc
 utils/wrap_py_base_field_source.cc
 utils/wrap_splinech.cc
 utils/wrap_utils.cc
)
set(all_wrap_src
 mpi/wrap_mpi_datatype.cc
 mpi/wrap_mpi_group.cc
 mpi/wrap_mpi_op.cc
 mpi/wrap_mpi_request.cc
 mpi/wrap_mpi_status.cc
 mpi/wrap_orbit_mpi.cc
)
