set(pyorbit_src
 linac/rfgap/BaseRfGap.cc
 linac/rfgap/BaseRfGap_slow.cc
 linac/rfgap/MatrixRfGap.cc
 linac/rfgap/RfGapThreePointTTF.cc
 linac/rfgap/RfGapThreePointTTF_slow.cc
 linac/rfgap/RfGapTTF.cc
 linac/rfgap/RfGapTTF_slow.cc
 linac/rfgap/SuperFishFieldSource.cc
 linac/tracking/linac_tracking.cc
 mpi/orbit_mpi.cc
 orbit/Apertures/Aperture.cc
 orbit/Apertures/EnergyAperture.cc
 orbit/Apertures/PhaseAperture.cc
 orbit/Bunch.cc
 orbit/BunchDiagnostics/BunchTuneAnalysis.cc
 orbit/BunchDiagnostics/BunchTwissAnalysis.cc
 orbit/Errors/errorbase.cc
 orbit/Errors/wrap_errorbase.cc
 orbit/FieldTracker/FieldTracker.cc
 orbit/FieldTracker/wrap_fieldtracker.cc
 orbit/Impedances/LImpedance.cc
 orbit/Impedances/TImpedance.cc
 orbit/MaterialInteractions/Collimator.cc
 orbit/MaterialInteractions/cross_sections.cc
 orbit/MaterialInteractions/Foil.cc
 orbit/MaterialInteractions/MaterialInteractions.cc
 orbit/MaterialInteractions/numrecipes.cc
 orbit/OrbitConst.cc
 orbit/ParticlesAttributes/AtomPopulations.cc
 orbit/ParticlesAttributes/Evolution.cc
 orbit/ParticlesAttributes/LostParticleAttributes.cc
 orbit/ParticlesAttributes/ParticleAttributes.cc
 orbit/ParticlesAttributes/ParticleAttributesFactory.cc
 orbit/ParticlesAttributes/ParticleIdNumber.cc
 orbit/ParticlesAttributes/ParticleInitialCoordinates.cc
 orbit/ParticlesAttributes/ParticleMacroSize.cc
 orbit/ParticlesAttributes/ParticlePhaseAttributes.cc
 orbit/ParticlesAttributes/part_time.cc
 orbit/ParticlesAttributes/pq_coordinates.cc
 orbit/ParticlesAttributes/WaveFunctionAmplitudes.cc
 orbit/RFCavities/Barrier_Cav.cc
 orbit/RFCavities/Dual_Harmonic_Cav.cc
 orbit/RFCavities/Frequency_Cav.cc
 orbit/RFCavities/Harmonic_Cav.cc
 orbit/SynchPartRedefinition/SynchPartRedefinitionZdE.cc
 orbit/SyncPart.cc
 spacecharge/BaseBoundary2D.cc
 spacecharge/ForceSolver2D.cc
 spacecharge/ForceSolverFFT2D.cc
 spacecharge/Grid1D.cc
 spacecharge/Grid2D.cc
 spacecharge/Grid3D.cc
 spacecharge/LSpaceChargeCalc.cc
 spacecharge/PoissonSolver2D.cc
 spacecharge/PoissonSolver3D.cc
 spacecharge/PoissonSolverFFT2D.cc
 spacecharge/PoissonSolverFFT3D.cc
 spacecharge/ShapedBoundary2D.cc
 spacecharge/SpaceChargeCalc2p5D.cc
 spacecharge/SpaceChargeCalc2p5Drb.cc
 spacecharge/SpaceChargeCalc3D.cc
 spacecharge/SpaceChargeCalcSliceBySlice2D.cc
 spacecharge/SpaceChargeCalcUnifEllipse.cc
 spacecharge/SpaceChargeForceCalc2p5D.cc
 spacecharge/UniformEllipsoidFieldCalculator.cc
 teapot/MatrixGenerator.cc
 teapot/teapotbase.cc
 trackerrk4/ExtEffectsContainer.cc
 trackerrk4/ExternalEffects.cc
 trackerrk4/PyExternalEffects.cc
 trackerrk4/RungeKuttaTracker.cc
 utils/AttributesBucket.cc
 utils/BaseFieldSource.cc
 utils/bessel.cc
 utils/BufferStore.cc
 utils/bunch/BunchExtremaCalculator.cc
 utils/bunch/InitialCoordsAttrFunctions.cc
 utils/bunch/ParticlesWithIdFunctions.cc
 utils/bunch/TwissFilteringFunctions.cc
 utils/CppPyWrapper.cc
 utils/FieldSourceContainer.cc
 utils/integration/GaussLegendreIntegrator.cc
 utils/integration/gauss_legendre_points.cc
 utils/LorentzTransformationEM.cc
 utils/MathPolynomial.cc
 utils/matrix/Matrix.cc
 utils/matrix/MatrixOperations.cc
 utils/matrix/PhaseVector.cc
 utils/OU_Function.cc
 utils/OU_SplineCH.cc
 utils/polynomial/OU_Polynomial.cc
 utils/PyBaseFieldSource.cc
 utils/Random.cc
 utils/statistics/StatMoments2D.cc
 utils/StringUtils.cc
)
